name = "deepseek-api-worker"
main = "worker.js"
compatibility_date = "2023-08-15"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
# 开发环境的变量可以在这里设置
# 生产环境的敏感变量应使用 wrangler secret 命令设置
[env.production.vars]
DEEPSEEK_API_KEY= { type = "secret" }

# 如果需要，可以添加KV存储、Durable Objects等资源